version: 2

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - npm-4-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - npm-4-

save_modules_cache: &save_modules_cache
  save_cache:
    key: npm-4-{{ checksum "package.json" }}
    paths: ./node_modules

jobs:
  docs:
    docker:
      - image: circleci/ruby:2.4-node
        env:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - restore_cache:
          key: deps-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          key: deps-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - *restore_modules_cache
      - run: yarn
      - *save_modules_cache
      - run: yarn build
      - run: yarn copy-to-docs
      - run: yarn build:docs
      - store_artifacts:
          path: build
          destination: docs

workflows:
  version: 2
  test:
    jobs:
      - docs
